### ISSUE TITLE
Drivers directory

### ISSUE THREAD

**Issue by yuv422** [ghidraninja/game-and-watch-base#3]
I wasn't sure where to get the Drivers directory from as it isn't included in this repo. I ended up using https://github.com/STMicroelectronics/STM32CubeH7

Is this correct?

**Comment by kbeckmann** [comment]
That can be used. The way this project is intended to be used, it to provide a baseline project file `gw_base.ioc` that can be opened and configured in the STM32CubeMX software. In that software you can then configure pins, DMA jobs, etc and then finally press `generate` to generate the configuration. It will also provide the correct HAL drivers etc.
