### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by chcbaram** [ghidraninja/game-and-watch-base#4]
I made the firmware and your base project help me a lot. thanks. 
This is the project I am working.

https://github.com/chcbaram/game_n_watch

https://youtu.be/LUWV9d6S2lA

https://youtu.be/oqfg3_C9Sx8

It is unfortunate that the communication port on the board is not outside.
I think it would be nice if a board with an improved version could be made.

Thanks again.

**Comment by kbeckmann** [comment]
Nice! Happy to see some homebrew 😀. Yes, it is unfortunate with the usb-c port.
