### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by AlfonsoJLuna** [ghidraninja/game-and-watch-base#6]
We should add a license to this project, MIT maybe?

**Comment by nezza** [comment]
We discussed licensing this under 3-clause BSD which would be in line with the ST code

**Comment by kbeckmann** [comment]
Sounds good with BSD 3-clause.

**Comment by AlfonsoJLuna** [comment]
BSD-3 sounds good!

**Comment by nezza** [comment]
Done, thx!

**Comment by nezza** [comment]
https://github.com/ghidraninja/game-and-watch-base/blob/main/COPYING
